# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N4qTKS35I8SvJsEuk5LihDtO1nSaLztG

Задание 1
"""

def f(n):
    s = str(abs(n))
    k = 0

    for i in s:
        k += int(i)
    return k


if __name__ == "__main__":
    print(f(123456))

"""Задание 2"""

def f(n):
    s = str(abs(n))
    k = 0
    for i in s:
        k += int(i)
    if n % k == 0:
        return True
    else:
        return False


if __name__ == "__main__":
    print(f(12))

"""Задание 3"""

def f(n):
    while n > 0:
        if n % 2 == 0:
            n = n / 2
            return True
        else:
            return False
          
if __name__ == "__main__":
    print(f(12))

"""Задание 4"""

def f(n):
    for i in range(2, n):
        if n % i == 0:
            return False 
    return True
      
if __name__ == "__main__":
    print(f(12))

"""Задание 5"""

def f(n):
    s = str(abs(n))
    for i in s:
        if n % int(i) != 0:
            return False
    return True


if __name__ == "__main__":
    print(f(124))

"""Задание 6"""

def f(L):
    p = 0
    k = len(L)
    for i in range(k-2):
        for j in range(i + 1, k-1):
            for n in range(j + 1, k):
                a = float(L[i])
                b = float(L[j])
                c = float(L[n])
                if a + b > c and a + c > b and b + c > a and a + b + c > p:
                    p = a + b + c
    if p == 0:
       print('Error')
       return None
    else:
       return p
       
  
if __name__ == "__main__":
    L = [2,4,3,5,6,7,2.4]
    print(f(L))

